### ISSUE TITLE
Our binder is broken

### ISSUE THREAD

**Issue by GaelVaroquaux** [dirty-cat/dirty_cat#381]
Clicking on the binder link for the examples no longer works (it gives a "file not found error"). I suspect that this is because of the rewrite of the documentation-building system a little while ago.

**Comment by GaelVaroquaux** [comment]
It seems that the problem is still there

**Comment by GaelVaroquaux** [comment]
I think that the problem is that there is a "dev" that is appended by our build system that is outside what is understood by sphinx-gallery

**Comment by GaelVaroquaux** [comment]
It might be useful to inspect how scikit-learn does it, as they have the same problem. They use scripts in the .binder folder:
https://github.com/scikit-learn/scikit-learn/tree/main/.binder

**Comment by jovan-stojanovic** [comment]
Now we have the dev/dev/dev link to notebooks.. It seems that the parameter `notebooks_dir should be removed: https://sphinx-gallery.github.io/stable/configuration.html#binder-links

**Comment by ymzayek** [comment]
The nilearn binder configuration, which is based on scikit-learn, uses the nilearn/nilearn repo instead of nilearn/nilearn.github.io to build the notebooks from the examples python files using the sphinx gallery configuration in `conf.py` and `.binder/postBuild`. This is because binder does not natively support more than one environment for one repository (at least this was the case when I implemented this but haven't kept an eye out about any relevant updates). The way we set it up allows us to build the notebooks from main for the dev docs/environment and the stable ones from the latest release tag which will be associated with our stable docs. Let me know if you want help to implement this or if you find a (better) way around it.

**Comment by GaelVaroquaux** [comment]
Still not quite there :laughing: 

When I click on a binder link, it open the following URL "https://hub.gke2.mybinder.org/user/dirty-cat-dirty-cat.github.io-vd22o21v/tree/dev/auto_examples/01_dirty_categories.ipynb"

Which seems to tell me that it is looking for notebooks in the "dev/auto_examples/" folder. However, inspecting the dirty-cat.github.io tells me that they are the "dev/notebooks/auto_examples" folder:
https://github.com/dirty-cat/dirty-cat.github.io/tree/main/dev/notebooks/auto_examples

**Comment by jovan-stojanovic** [comment]
From what I see, the dev version of the website doesn't have this problem, so I guess the solution is updating the website again from dev to stable with the new release? 
I think this is because of the following part in [conf.py](https://github.com/dirty-cat/dirty_cat/blob/main/doc/conf.py#L262):
```
if 'dev' in release:
    binder_branch = 'main'
else:
    binder_branch = release
```
that refers to the code of the released version branch when creating the binder. I think this avoids ending up with a different code with the binder than on the website if example are modified on the main branch.

**Comment by jovan-stojanovic** [comment]
Maybe a workaround can be to force it to search in the ['./notebooks/auto_examples'](https://github.com/dirty-cat/dirty_cat/blob/main/doc/conf.py#L277) folder.

**Comment by GaelVaroquaux** [comment]
If the dev version does not have a problem, let's not worry. We'll do a minor release soon, as we have a set of small bug fixes coming up

**Comment by ymzayek** [comment]
It's because the stable docs were built with links that do not reflect the new changes. It won't work for the stable docs until your next release / stable build is pushed to github pages repo.

**Comment by LilianBoulard** [comment]
Solved by release 0.4.1
